publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "position_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6"]
    pos1: [0.785, 0.785, 0.785, 0.785, 0.785, 0.785]
    pos2: [0, 0, 0, 0, 0, 0]
    pos3: [-0.785, -0.785, -0.785, -0.785, -0.785, -0.785]
    pos4: [0, 0, 0, 0, 0, 0]
    pos5: [0.785, 0.785, 0.785, 0.785, 0.785, 0.785]
    pos6: [0, 0, 0, 0, 0, 0]

    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint

    check_starting_point: false
    starting_point_limits:
      arm_1_joint: [-0.1,0.1]
      arm_2_joint: [-0.1,0.1]
      arm_3_joint: [-0.1,0.1]
      arm_4_joint: [-0.1,0.1]
      arm_5_joint: [-0.1,0.1]
      arm_6_joint: [-0.1,0.1]